# This is a basic workflow to help you get started with Actions

name: Update Content

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Schedule to run daily at 11:30 PM (UTC)
  schedule:
      - cron: "30 23 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: gition
        uses: otaviobertucini/gition@v0.18
        with:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_PAGES: 3f52f0203a3e4aedb0931227bb485545;a9f04e83a1844114a5df8a3ab7b8c21e
          ROOT_DIR: Notion Articles

      - name: Save changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Commit new content from Notion
