# This is a basic workflow to help you get started with Actions

name: Gition Test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: gition
        uses: otaviobertucini/gition@v0.13
        with:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_PAGE: 8da3f433-b0dd-47b2-8821-d9c124c1a356
